// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello
List rcpp_hello();
RcppExport SEXP SMC5_rcpp_hello() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello());
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP SMC4_GibbsSamplingCpp(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP SMC4_KalmanFilterCpp(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP SMC4_KalmanSmoothingCpp(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP SMC4_ProbSampleReplace(SEXP, SEXP, SEXP);
RcppExport SEXP SMC4_blockForwardSmoothing(SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP SMC4_blockParticleBackwardSamplingCpp(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP SMC4_blockParticleBackwardSmoothingCpp(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP SMC4_blockParticleFilter(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP SMC4_dmvnrmArma(SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP SMC4_dnrmArma(SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP SMC4_gibbsParticleFilter(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP SMC4_logAddition(SEXP, SEXP);
RcppExport SEXP SMC4_logAdditionSum(SEXP);
RcppExport SEXP SMC4_mvrnormArma(SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP SMC4_neighbour(SEXP, SEXP, SEXP);
RcppExport SEXP SMC4_rnormArma(SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"SMC5_rcpp_hello", (DL_FUNC) &SMC5_rcpp_hello, 0},
    {"SMC4_GibbsSamplingCpp",                  (DL_FUNC) &SMC4_GibbsSamplingCpp,                  7},
    {"SMC4_KalmanFilterCpp",                   (DL_FUNC) &SMC4_KalmanFilterCpp,                   7},
    {"SMC4_KalmanSmoothingCpp",                (DL_FUNC) &SMC4_KalmanSmoothingCpp,                9},
    {"SMC4_ProbSampleReplace",                 (DL_FUNC) &SMC4_ProbSampleReplace,                 3},
    {"SMC4_blockForwardSmoothing",             (DL_FUNC) &SMC4_blockForwardSmoothing,             4},
    {"SMC4_blockParticleBackwardSamplingCpp",  (DL_FUNC) &SMC4_blockParticleBackwardSamplingCpp,  8},
    {"SMC4_blockParticleBackwardSmoothingCpp", (DL_FUNC) &SMC4_blockParticleBackwardSmoothingCpp, 7},
    {"SMC4_blockParticleFilter",               (DL_FUNC) &SMC4_blockParticleFilter,               9},
    {"SMC4_dmvnrmArma",                        (DL_FUNC) &SMC4_dmvnrmArma,                        5},
    {"SMC4_dnrmArma",                          (DL_FUNC) &SMC4_dnrmArma,                          4},
    {"SMC4_gibbsParticleFilter",               (DL_FUNC) &SMC4_gibbsParticleFilter,               7},
    {"SMC4_logAddition",                       (DL_FUNC) &SMC4_logAddition,                       2},
    {"SMC4_logAdditionSum",                    (DL_FUNC) &SMC4_logAdditionSum,                    1},
    {"SMC4_mvrnormArma",                       (DL_FUNC) &SMC4_mvrnormArma,                       4},
    {"SMC4_neighbour",                         (DL_FUNC) &SMC4_neighbour,                         3},
    {"SMC4_rnormArma",                         (DL_FUNC) &SMC4_rnormArma,                         3},
    {NULL, NULL, 0}
};

RcppExport void R_init_SMC5(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
