# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

KalmanFilterCpp <- function(m_0, C_0, F_matrix, G, V, W, y) {
    .Call('SMC5_KalmanFilterCpp', PACKAGE = 'SMC5', m_0, C_0, F_matrix, G, V, W, y)
}

KalmanSmoothingCpp <- function(m_0, C_0, F_matrix, G, V, W, y) {
    .Call('SMC5_KalmanSmoothingCpp', PACKAGE = 'SMC5', m_0, C_0, F_matrix, G, V, W, y)
}

KalmanSamplerCpp <- function(n, kalmanRes, time) {
    .Call('SMC5_KalmanSamplerCpp', PACKAGE = 'SMC5', n, kalmanRes, time)
}

#' Multivariate Normal Density
#'
#' This function computes the density of a multivariate normal.
#'
#' @param x a nxp matrix whose columns are the components of the multivariate normal.
#' @param mean a p-dimensional mean vector
#' @param sigma a pxp covariance matrix
#' @param logd if \code{TRUE} log densities are returned
#' @details This function is taken from \url{http://gallery.rcpp.org/articles/dmvnorm_arma/}
#' @return A n-dimensional column vector with the values of the density.
#' @author Nino Hardt, Dicko Ahmadou
#' @export
dmvnrmArma <- function(x, mean, sigma, logd = FALSE, diag = FALSE) {
    .Call('SMC5_dmvnrmArma', PACKAGE = 'SMC5', x, mean, sigma, logd, diag)
}

dnrmArma <- function(x, mean, sigma, logd = FALSE) {
    .Call('SMC5_dnrmArma', PACKAGE = 'SMC5', x, mean, sigma, logd)
}

#' Simulate from a Multivariate Normal Density
#'
#' This function produces samples from a Multivariate Normal distribution.
#'
#' @param n size of sample required
#' @param mean a p-dimensional mean vector
#' @param sigma a pxp covariance matrix
#' @details This function is taken from \url{http://gallery.rcpp.org/articles/simulate-multivariate-normal/}
#' @return A nxp matrix with the generated sample
#' @author Dicko Ahmadou
#' @export
mvrnormArma <- function(n, mean, sigma, diag = FALSE) {
    .Call('SMC5_mvrnormArma', PACKAGE = 'SMC5', n, mean, sigma, diag)
}

rnormArma <- function(n, mean, sigma) {
    .Call('SMC5_rnormArma', PACKAGE = 'SMC5', n, mean, sigma)
}

blockParticleFilter <- function(N, n, blocks, fParams, gParams, resampling = TRUE) {
    .Call('SMC5_blockParticleFilter', PACKAGE = 'SMC5', N, n, blocks, fParams, gParams, resampling)
}

sequentialImportanceSampling <- function(N, n, fParams, gParams) {
    .Call('SMC5_sequentialImportanceSampling', PACKAGE = 'SMC5', N, n, fParams, gParams)
}

bootstrapParticleFilter <- function(N, n, fParams, gParams) {
    .Call('SMC5_bootstrapParticleFilter', PACKAGE = 'SMC5', N, n, fParams, gParams)
}

logAddition <- function(x, y) {
    .Call('SMC5_logAddition', PACKAGE = 'SMC5', x, y)
}

logAdditionSum <- function(x) {
    .Call('SMC5_logAdditionSum', PACKAGE = 'SMC5', x)
}

ProbSampleReplace <- function(nOrig, size, prob) {
    .Call('SMC5_ProbSampleReplace', PACKAGE = 'SMC5', nOrig, size, prob)
}

checkDiagonal <- function(X) {
    .Call('SMC5_checkDiagonal', PACKAGE = 'SMC5', X)
}

checkSymmetric <- function(X) {
    .Call('SMC5_checkSymmetric', PACKAGE = 'SMC5', X)
}

